#!/bin/sh -e

# Información del sistema
kernel_version=$(uname -r)
shell=$(basename "$SHELL")
. /etc/os-release

# Window Manager
while read -r line; do
    [ "${line#exec }" = "$line" ] || wm="${line#exec }"
done < "$HOME/.xinitrc"

# Colores
# Colors and palette method stolen from dylanaraps pftech
# https://github.com/dylanaraps/pfetch
c0='[0m';
c1='[31m'; c2='[32m'
c3='[33m'; c4='[34m'
c5='[35m'; c6='[36m'
c7='[37m'; c8='[38m'
palette="[7m$c1 $c1 $c2 $c2 $c3 $c3 $c4 $c4 $c1 $c5 $c6 $c6 [m"


# Gato simple
printf '%s\n' "

        ${c0}os -> ${PRETTY_NAME}
${c1} /\_/\  ${c2}kernel -> $kernel_version
${c1}( o.o ) ${c6}shell -> $shell
${c1} > ^ <  ${c3}wm -> $wm

        ${palette}
"
