#!/bin/sh -e

# System Info
kernel_version=$(uname -r)
shell=$(basename "$SHELL")
. /etc/os-release

# Window Manager
if [ -f "$HOME/.config/sx/sxrc" ]; then
    while read -r line; do
        [ "${line#exec }" = "$line" ] || wm="${line#exec }"
    done < "$HOME/.config/sx/sxrc"
elif [ -f "$HOME/.xinitrc" ]; then
    while read -r line; do
        [ "${line#exec }" = "$line" ] || wm="${line#exec }"
    done < "$HOME/.xinitrc"
fi

# Colors and palette method stolen from dylanaraps pftech
# https://github.com/dylanaraps/pfetch
c0='[1;0m';
c1='[1;31m'; c2='[1;32m'
c3='[1;33m'; c4='[1;34m'
c5='[1;35m'; c6='[1;36m'
c7='[1;37m'; c8='[1;38m'
palette="[7m$c1 $c1 $c2 $c2 $c3 $c3 $c4 $c4 $c1 $c5 $c6 $c6 [m"

# Gato simple
printf '%s\n' "
            ${c1}os ~ ${c0}${PRETTY_NAME}
  ${c0}(\ /)     ${c2}kr ~ ${c0}$kernel_version
  ${c0}( . .)    ${c6}sh ~ ${c0}$shell
  ${c0}c(${c1}\"${c0})(${c1}\"${c0})   ${c3}wm ~ ${c0}$wm

            ${palette}
"
